### ISSUE TITLE
Edit .css to make the website more readable

### ISSUE THREAD

**Issue by Scinawa** [Scinawa/quantumalgorithms.org#69]
We need some help in modifying the css, so to make the website more readable. 

There are three modifications that would be nice to have, with two screenshots at the end of this issue for better illustrating the problem. 

1) The color of the Parts of the book should be changed. I would suggest the blue color of the box of definitions (see box 2.7 of constant function for instance). For example, the string "I - Bridging the gap " should be more visible. 

2) The size of the left menu bar is fixed, and perhaps too small. Because of this, it is not possible to fully read titles o the chapters. Can we increase the size of the menu on the left, and make it resizable with the mouse? 

3) The buttons "go to previous chapter" and "go to next chapter" are currently transparent, and when they overlap the rest of the text, they hide it. Can we make the buttons in the image below darker, so it's clear when they overlap with the text? 

If you decide to start this issue and you want some clarification or help, just contact me (@Scinawa ) on the discord of the unitary.fund, the slack channel of QOSF, @scinawa on twitter, or write me at ale@nus.edu.sg.  
In the first image, the three points discussed above. In the second image and example of the problem with the "right" and "left" buttons. 

![example](https://user-images.githubusercontent.com/2940017/167347024-f85b8669-9240-456e-8f13-64c4c676163d.png)

<img width="953" alt="Screenshot 2022-05-09 at 13 36 19" src="https://user-images.githubusercontent.com/2940017/167347077-5c34cc79-1c65-46e0-a9b4-d19d3cfd328b.png">

Thank you!

**Comment by cometta** [comment]
@Scinawa i can contribute to this, i think you miss out push 2 files into the repo quantumalgos.Rproj
quantumalgorithms.org.Rproj, i need it to open in rstudio

**Comment by cometta** [comment]
for item 2, we can increase the size of the left menu, but can't resize using mouse. that would need bookdown to add javascript implementation. Will that be ok?

**Comment by Avhijit-Nair** [comment]
I would like to work on this for the Unitary Hack.

**Comment by Scinawa** [comment]
That's great! What kind of help do you need on my side? :)

**Comment by Avhijit-Nair** [comment]
I'll reach out to you on discord for help :)

**Comment by Avhijit-Nair** [comment]
Whenever I'm trying to build the project, I'm getting below error and warning messages.
I've tried to fix the warning messages, but they always revert back to previous state whenever I click the **Build Book** button on RStudio IDE.
As for the Pandoc error message, I'm not really sure what the problem is.

`Error running filter D:\R-4.2.0\library\bookdown\rmarkdown\lua\custom-environment.lua:`
`....0\library\bookdown\rmarkdown\lua\custom-environment.lua:192: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:`
`....0\library\bookdown\rmarkdown\lua\custom-environment.lua:192: in function 'Div'`
`Error: pandoc document conversion failed with error 83
In addition: Warning messages:`
```diff
- The closing backticks on line 385 ("```") in quantumalgos.Rmd do not match the opening backticks " ```" on line 383. You are recommended to fix either the opening or closing delimiter of the code chunk to use exactly the same numbers of backticks and same level of indentation (or blockquote). 
- The closing backticks on line 1192 ("```") in quantumalgos.Rmd do not match the opening backticks " ```" on line 1190. You are recommended to fix either the opening or closing delimiter of the code chunk to use exactly the same numbers of backticks and same level of indentation (or blockquote).
- The closing backticks on line 3461 ("``` ") in quantumalgos.Rmd do not match the opening backticks " ```" on line 3459. You are recommended to fix either the opening or closing delimiter of the code chunk to use exactly the same numbers of backticks and same level of indentation (or blockquote).
- The closing backticks on line 5887 ("```") in quantumalgos.Rmd do not match the opening backticks "````" on line 5885. You are recommended to fix either the opening or closing delimiter of the code chunk to use exactly the same numbers of backticks and same level of indentation (or blockquote).
```
`Execution halted`
`Exited with status 1.`

**Comment by Scinawa** [comment]
Closed by cometta! 

Almost closed. Unfortunately this PR breaks the mobile version of the website.

**Comment by cometta** [comment]
new PR https://github.com/Scinawa/quantumalgorithms.org/pull/75

**Comment by cometta** [comment]
@Scinawa  able to close this ticket?
